// data.js — Static reference data for CAWI SE2026
// Kecamatan & Kelurahan/Desa Kabupaten Buleleng + KBLI 2025

const STATIC_KECAMATAN = {
  '5108': [
    {kode:'510801', nama:'GEROKGAK'},
    {kode:'510802', nama:'SERIRIT'},
    {kode:'510803', nama:'BUSUNGBIU'},
    {kode:'510804', nama:'BANJAR'},
    {kode:'510805', nama:'SUKASADA'},
    {kode:'510806', nama:'BULELENG'},
    {kode:'510807', nama:'SAWAN'},
    {kode:'510808', nama:'KUBUTAMBAHAN'},
    {kode:'510809', nama:'TEJAKULA'},
  ]
};

const STATIC_KELURAHAN = {
  '510801': [
    {kode:'5108012001',nama:'BANYUPOH'},{kode:'5108012002',nama:'BATU AMPAR'},
    {kode:'5108012003',nama:'CELUKAN BAWANG'},{kode:'5108012004',nama:'GEROKGAK'},
    {kode:'5108012005',nama:'MUSI'},{kode:'5108012006',nama:'PATAS'},
    {kode:'5108012007',nama:'PEJARAKAN'},{kode:'5108012008',nama:'PEMUTERAN'},
    {kode:'5108012009',nama:'PENGULON'},{kode:'5108012010',nama:'PENYABANGAN'},
    {kode:'5108012011',nama:'SANGGALANGIT'},{kode:'5108012012',nama:'SUMBER KLAMPOK'},
    {kode:'5108012013',nama:'SUMBERKIMA'},{kode:'5108012014',nama:'TINGA-TINGA'},
  ],
  '510802': [
    {kode:'5108022001',nama:'ANTURAN'},{kode:'5108022002',nama:'BANJARASEM'},
    {kode:'5108022003',nama:'BESTALA'},{kode:'5108022004',nama:'BUBUNAN'},
    {kode:'5108022005',nama:'JENGGALA'},{kode:'5108022006',nama:'JOANYAR'},
    {kode:'5108022007',nama:'KALISADA'},{kode:'5108022008',nama:'KALIANGET'},
    {kode:'5108022009',nama:'LABA SARI'},{kode:'5108022010',nama:'LOKAPAKSA'},
    {kode:'5108022011',nama:'MAYONG'},{kode:'5108022012',nama:'PANGKUNG PARUK'},
    {kode:'5108022013',nama:'PATEMON'},{kode:'5108022014',nama:'PENGASTULAN'},
    {kode:'5108022015',nama:'RINGDIKIT'},{kode:'5108022016',nama:'SANDA'},
    {kode:'5108021001',nama:'SERIRIT'},{kode:'5108022017',nama:'SULANYAH'},
    {kode:'5108022018',nama:'TANGGUWISIA'},{kode:'5108022019',nama:'TEGALLINGGAH'},
    {kode:'5108022020',nama:'UMEANYAR'},
  ],
  '510803': [
    {kode:'5108032001',nama:'BENGKEL'},{kode:'5108032002',nama:'BUSUNGBIU'},
    {kode:'5108032003',nama:'KEKERAN'},{kode:'5108032004',nama:'PELAPUAN'},
    {kode:'5108032005',nama:'PUCAKSARI'},{kode:'5108032006',nama:'SEPANG'},
    {kode:'5108032007',nama:'SUBUK'},{kode:'5108032008',nama:'TELAGA'},
    {kode:'5108032009',nama:'TINGGARSARI'},{kode:'5108032010',nama:'TISTA'},
    {kode:'5108032011',nama:'TITAB'},{kode:'5108032012',nama:'UMAJALAR'},
  ],
  '510804': [
    {kode:'5108042001',nama:'BANJAR'},{kode:'5108042002',nama:'BANJAR TEGEHA'},
    {kode:'5108042003',nama:'BANYUSERI'},{kode:'5108042004',nama:'CEMPAGA'},
    {kode:'5108042005',nama:'DENCARIK'},{kode:'5108042006',nama:'GESING'},
    {kode:'5108042007',nama:'GOBLEG'},{kode:'5108042008',nama:'KAYU PUTIH'},
    {kode:'5108042009',nama:'MUNDUK'},{kode:'5108042010',nama:'PEDAWA'},
    {kode:'5108042011',nama:'SIDETAPA'},{kode:'5108042012',nama:'TAMPEKAN'},
    {kode:'5108042013',nama:'TEMUKUS'},{kode:'5108042014',nama:'TIGAWASA'},
  ],
  '510805': [
    {kode:'5108052001',nama:'AMBENGAN'},{kode:'5108052002',nama:'GITGIT'},
    {kode:'5108052003',nama:'KAYUPUTIH'},{kode:'5108052004',nama:'LILIGUNDI'},
    {kode:'5108052005',nama:'NAGASEPAHA'},{kode:'5108052006',nama:'PADANG BULIA'},
    {kode:'5108052007',nama:'PANCASARI'},{kode:'5108052008',nama:'PANJI'},
    {kode:'5108052009',nama:'PANJI ANOM'},{kode:'5108052010',nama:'PEGAYAMAN'},
    {kode:'5108052011',nama:'SAMBANGAN'},{kode:'5108052012',nama:'SELAT'},
    {kode:'5108052013',nama:'SUKASADA'},{kode:'5108052014',nama:'TEGALLINGGAH'},
    {kode:'5108052015',nama:'WANAGIRI'},
  ],
  '510806': [
    {kode:'5108062001',nama:'ALASANGKER'},{kode:'5108061001',nama:'ASTINA'},
    {kode:'5108061002',nama:'BALE AGUNG'},{kode:'5108061003',nama:'BANJAR JAWA'},
    {kode:'5108061004',nama:'BANYUASRI'},{kode:'5108061005',nama:'BANYUNING'},
    {kode:'5108061006',nama:'BERATAN'},{kode:'5108061007',nama:'GALUNGAN'},
    {kode:'5108061008',nama:'JINENGDALEM'},{kode:'5108062002',nama:'KALIASEM'},
    {kode:'5108061009',nama:'KALIUNTU'},{kode:'5108061010',nama:'KAMPUNG BALI'},
    {kode:'5108061011',nama:'KAMPUNG BUGIS'},{kode:'5108061012',nama:'KAMPUNG SINGARAJA'},
    {kode:'5108061013',nama:'KENDRAN'},{kode:'5108062003',nama:'KALIBUKBUK'},
    {kode:'5108061014',nama:'KEROBOKAN'},{kode:'5108061015',nama:'LILIGUNDI'},
    {kode:'5108061016',nama:'PAKET AGUNG'},{kode:'5108061017',nama:'PENARUKAN'},
    {kode:'5108062004',nama:'PEMARON'},{kode:'5108061018',nama:'PENGLATAN'},
    {kode:'5108062005',nama:'TUKAD MUNGGA'},
  ],
  '510807': [
    {kode:'5108072001',nama:'BANYUATIS'},{kode:'5108072002',nama:'BEBETIN'},
    {kode:'5108072003',nama:'BUNGKULAN'},{kode:'5108072004',nama:'GALUNGAN'},
    {kode:'5108072005',nama:'GIRI MAS'},{kode:'5108072006',nama:'KEROBOKAN'},
    {kode:'5108072007',nama:'LEMUKIH'},{kode:'5108072008',nama:'MENYALI'},
    {kode:'5108072009',nama:'SANGSIT'},{kode:'5108072010',nama:'SAWAN'},
    {kode:'5108072011',nama:'SEKUMPUL'},{kode:'5108072012',nama:'SUDAJI'},
    {kode:'5108072013',nama:'SUWUG'},{kode:'5108072014',nama:'TIRTA SARI'},
  ],
  '510808': [
    {kode:'5108082001',nama:'BAKTI SERAGA'},{kode:'5108082002',nama:'BENGKALA'},
    {kode:'5108082003',nama:'BILA'},{kode:'5108082004',nama:'BONTIHING'},
    {kode:'5108082005',nama:'BULIAN'},{kode:'5108082006',nama:'DEPEHA'},
    {kode:'5108082007',nama:'KUBUTAMBAHAN'},{kode:'5108082008',nama:'MENGENING'},
    {kode:'5108082009',nama:'PACUNG'},{kode:'5108082010',nama:'TAJUN'},
    {kode:'5108082011',nama:'TAMBLANG'},{kode:'5108082012',nama:'TUNJUNG'},
  ],
  '510809': [
    {kode:'5108092001',nama:'BONDALEM'},{kode:'5108092002',nama:'JULAH'},
    {kode:'5108092003',nama:'LES'},{kode:'5108092004',nama:'PACUNG'},
    {kode:'5108092005',nama:'PENUKTUKAN'},{kode:'5108092006',nama:'SAMBIRENTENG'},
    {kode:'5108092007',nama:'SEMBIRAN'},{kode:'5108092008',nama:'TEMBOK'},
    {kode:'5108092009',nama:'TEJAKULA'},
  ],
};

const KBLI_DATA = [
  // ===== A: PERTANIAN, KEHUTANAN DAN PERIKANAN =====
  {Kode:'01111',Judul:'Pertanian Padi',Kategori:'A'},
  {Kode:'01112',Judul:'Pertanian Jagung',Kategori:'A'},
  {Kode:'01113',Judul:'Pertanian Ubi Kayu',Kategori:'A'},
  {Kode:'01114',Judul:'Pertanian Kedelai',Kategori:'A'},
  {Kode:'01115',Judul:'Pertanian Kacang Tanah',Kategori:'A'},
  {Kode:'01116',Judul:'Pertanian Kacang Hijau',Kategori:'A'},
  {Kode:'01119',Judul:'Pertanian Serealia Lainnya',Kategori:'A'},
  {Kode:'01121',Judul:'Pertanian Sayuran Daun',Kategori:'A'},
  {Kode:'01122',Judul:'Pertanian Cabai dan Sejenisnya',Kategori:'A'},
  {Kode:'01123',Judul:'Pertanian Bawang dan Sejenisnya',Kategori:'A'},
  {Kode:'01124',Judul:'Pertanian Sayuran Buah Lainnya',Kategori:'A'},
  {Kode:'01125',Judul:'Pertanian Jamur',Kategori:'A'},
  {Kode:'01126',Judul:'Pertanian Buah-Buahan Tropis',Kategori:'A'},
  {Kode:'01127',Judul:'Pertanian Buah-Buahan Lainnya',Kategori:'A'},
  {Kode:'01128',Judul:'Pertanian Tanaman Hias dan Bunga',Kategori:'A'},
  {Kode:'01129',Judul:'Pertanian Sayuran, Buah, dan Rempah Lainnya',Kategori:'A'},
  {Kode:'01130',Judul:'Pertanian Tebu',Kategori:'A'},
  {Kode:'01140',Judul:'Pertanian Tembakau',Kategori:'A'},
  {Kode:'01150',Judul:'Pertanian Tanaman Serat',Kategori:'A'},
  {Kode:'01191',Judul:'Pertanian Tanaman Obat-Obatan',Kategori:'A'},
  {Kode:'01192',Judul:'Pertanian Tanaman untuk Membuat Minuman (Kopi, Teh, Kakao)',Kategori:'A'},
  {Kode:'01199',Judul:'Pertanian Tanaman Semusim Lainnya',Kategori:'A'},
  {Kode:'01210',Judul:'Pertanian Karet dan Tanaman Penghasil Getah Lainnya',Kategori:'A'},
  {Kode:'01220',Judul:'Pertanian Kelapa',Kategori:'A'},
  {Kode:'01230',Judul:'Pertanian Kelapa Sawit',Kategori:'A'},
  {Kode:'01240',Judul:'Pertanian Kopi',Kategori:'A'},
  {Kode:'01250',Judul:'Pertanian Teh',Kategori:'A'},
  {Kode:'01260',Judul:'Pertanian Kakao',Kategori:'A'},
  {Kode:'01270',Judul:'Pertanian Tanaman Rempah-Rempah Tahunan',Kategori:'A'},
  {Kode:'01281',Judul:'Pertanian Buah-Buahan Tahunan',Kategori:'A'},
  {Kode:'01282',Judul:'Pertanian Pisang',Kategori:'A'},
  {Kode:'01291',Judul:'Pertanian Bambu',Kategori:'A'},
  {Kode:'01292',Judul:'Pertanian Tanaman Tahunan Lainnya',Kategori:'A'},
  {Kode:'01300',Judul:'Pembibitan Tanaman',Kategori:'A'},
  {Kode:'01410',Judul:'Peternakan Sapi dan Kerbau',Kategori:'A'},
  {Kode:'01420',Judul:'Peternakan Kuda dan Sejenisnya',Kategori:'A'},
  {Kode:'01430',Judul:'Peternakan Babi',Kategori:'A'},
  {Kode:'01440',Judul:'Peternakan Domba dan Kambing',Kategori:'A'},
  {Kode:'01451',Judul:'Peternakan Ayam Buras',Kategori:'A'},
  {Kode:'01452',Judul:'Peternakan Ayam Ras Pedaging',Kategori:'A'},
  {Kode:'01453',Judul:'Peternakan Ayam Ras Petelur',Kategori:'A'},
  {Kode:'01454',Judul:'Peternakan Itik dan Sejenisnya',Kategori:'A'},
  {Kode:'01459',Judul:'Peternakan Unggas Lainnya',Kategori:'A'},
  {Kode:'01460',Judul:'Peternakan Lebah dan Ulat Sutera',Kategori:'A'},
  {Kode:'01491',Judul:'Peternakan Kelinci dan Sejenisnya',Kategori:'A'},
  {Kode:'01492',Judul:'Peternakan Hewan Peliharaan',Kategori:'A'},
  {Kode:'01499',Judul:'Peternakan Lainnya',Kategori:'A'},
  {Kode:'01500',Judul:'Pertanian dan Peternakan Campuran',Kategori:'A'},
  {Kode:'01610',Judul:'Jasa Penunjang Pertanian',Kategori:'A'},
  {Kode:'01620',Judul:'Jasa Pasca Panen',Kategori:'A'},
  {Kode:'01630',Judul:'Pemrosesan Benih untuk Perbanyakan',Kategori:'A'},
  {Kode:'01700',Judul:'Perburuan dan Penangkapan Satwa Liar',Kategori:'A'},
  {Kode:'02100',Judul:'Silvikultur dan Kegiatan Kehutanan Lainnya',Kategori:'A'},
  {Kode:'02200',Judul:'Pembalakan/Penebangan Kayu',Kategori:'A'},
  {Kode:'02300',Judul:'Pengumpulan Hasil Hutan Bukan Kayu',Kategori:'A'},
  {Kode:'02400',Judul:'Jasa Kehutanan',Kategori:'A'},
  {Kode:'03111',Judul:'Perikanan Laut',Kategori:'A'},
  {Kode:'03112',Judul:'Perikanan Tangkap di Perairan Umum',Kategori:'A'},
  {Kode:'03120',Judul:'Perikanan Budidaya Air Tawar',Kategori:'A'},
  {Kode:'03210',Judul:'Perikanan Budidaya Air Laut',Kategori:'A'},
  {Kode:'03220',Judul:'Perikanan Budidaya Air Payau',Kategori:'A'},
  // ===== B: PERTAMBANGAN DAN PENGGALIAN =====
  {Kode:'05100',Judul:'Pertambangan Batubara',Kategori:'B'},
  {Kode:'05200',Judul:'Pertambangan Lignit',Kategori:'B'},
  {Kode:'06100',Judul:'Pertambangan Minyak Bumi',Kategori:'B'},
  {Kode:'06200',Judul:'Pertambangan Gas Alam',Kategori:'B'},
  {Kode:'07100',Judul:'Pertambangan Bijih Besi',Kategori:'B'},
  {Kode:'07210',Judul:'Pertambangan Bijih Uranium dan Thorium',Kategori:'B'},
  {Kode:'07290',Judul:'Pertambangan Bijih Logam Lainnya',Kategori:'B'},
  {Kode:'08101',Judul:'Penggalian Batu Ornamen dan Batu Bangunan',Kategori:'B'},
  {Kode:'08102',Judul:'Penggalian Batu Gamping',Kategori:'B'},
  {Kode:'08103',Judul:'Penggalian Pasir',Kategori:'B'},
  {Kode:'08104',Judul:'Penggalian Tanah Liat',Kategori:'B'},
  {Kode:'08109',Judul:'Penggalian Batu-Batuan Lainnya',Kategori:'B'},
  {Kode:'08910',Judul:'Penambangan Kimia dan Pupuk Mineral',Kategori:'B'},
  {Kode:'08920',Judul:'Penggalian dan Pengambilan Gambut',Kategori:'B'},
  {Kode:'08930',Judul:'Penambangan Garam',Kategori:'B'},
  {Kode:'08990',Judul:'Penggalian Lainnya',Kategori:'B'},
  {Kode:'09100',Judul:'Jasa Penunjang Pertambangan Minyak dan Gas Bumi',Kategori:'B'},
  {Kode:'09900',Judul:'Jasa Penunjang Pertambangan Lainnya',Kategori:'B'},
  // ===== C: INDUSTRI PENGOLAHAN =====
  {Kode:'10101',Judul:'Industri Pengolahan dan Pengawetan Daging',Kategori:'C'},
  {Kode:'10102',Judul:'Industri Pengolahan dan Pengawetan Daging Unggas',Kategori:'C'},
  {Kode:'10201',Judul:'Industri Pengolahan dan Pengawetan Ikan dan Biota Air (Bukan Udang)',Kategori:'C'},
  {Kode:'10202',Judul:'Industri Pengolahan dan Pengawetan Udang',Kategori:'C'},
  {Kode:'10209',Judul:'Industri Pengolahan dan Pengawetan Ikan dan Biota Air Lainnya',Kategori:'C'},
  {Kode:'10301',Judul:'Industri Pengolahan dan Pengawetan Buah-Buahan',Kategori:'C'},
  {Kode:'10302',Judul:'Industri Pengolahan dan Pengawetan Sayur-Sayuran',Kategori:'C'},
  {Kode:'10309',Judul:'Industri Pengolahan Buah dan Sayur Lainnya',Kategori:'C'},
  {Kode:'10401',Judul:'Industri Minyak Makan dan Lemak dari Nabati dan Hewani',Kategori:'C'},
  {Kode:'10402',Judul:'Industri Kopra',Kategori:'C'},
  {Kode:'10403',Judul:'Industri Minyak Mentah Kelapa Sawit (Crude Palm Oil)',Kategori:'C'},
  {Kode:'10404',Judul:'Industri Minyak Goreng dari Kelapa',Kategori:'C'},
  {Kode:'10405',Judul:'Industri Minyak Goreng dari Kelapa Sawit',Kategori:'C'},
  {Kode:'10409',Judul:'Industri Minyak dan Lemak Nabati dan Hewani Lainnya',Kategori:'C'},
  {Kode:'10501',Judul:'Industri Pengolahan Susu Segar dan Krim',Kategori:'C'},
  {Kode:'10502',Judul:'Industri Pengolahan Susu Bubuk dan Susu Kental',Kategori:'C'},
  {Kode:'10503',Judul:'Industri Es Krim',Kategori:'C'},
  {Kode:'10509',Judul:'Industri Pengolahan Susu dan Makanan dari Susu Lainnya',Kategori:'C'},
  {Kode:'10611',Judul:'Industri Penggilingan Padi dan Penyosohan Beras',Kategori:'C'},
  {Kode:'10612',Judul:'Industri Penggilingan Aneka Kacang',Kategori:'C'},
  {Kode:'10613',Judul:'Industri Penggilingan Aneka Umbi',Kategori:'C'},
  {Kode:'10614',Judul:'Industri Tepung Terigu',Kategori:'C'},
  {Kode:'10615',Judul:'Industri Berbagai Macam Tepung dari Padi-Padian',Kategori:'C'},
  {Kode:'10616',Judul:'Industri Pati Ubi Kayu',Kategori:'C'},
  {Kode:'10617',Judul:'Industri Tepung dari Sagu',Kategori:'C'},
  {Kode:'10619',Judul:'Industri Penggilingan Lainnya',Kategori:'C'},
  {Kode:'10620',Judul:'Industri Pati',Kategori:'C'},
  {Kode:'10710',Judul:'Industri Produk Roti dan Kue',Kategori:'C'},
  {Kode:'10720',Judul:'Industri Gula',Kategori:'C'},
  {Kode:'10730',Judul:'Industri Kembang Gula',Kategori:'C'},
  {Kode:'10740',Judul:'Industri Makaroni, Mie, Spaghetti, Bihun, Soun, dan Produk Sejenisnya',Kategori:'C'},
  {Kode:'10750',Judul:'Industri Makanan dari Kedelai dan Kacang-Kacangan Lainnya',Kategori:'C'},
  {Kode:'10761',Judul:'Industri Tahu',Kategori:'C'},
  {Kode:'10762',Judul:'Industri Tempe',Kategori:'C'},
  {Kode:'10763',Judul:'Industri Kecap',Kategori:'C'},
  {Kode:'10764',Judul:'Industri Kerupuk, Keripik, Peyek dan Sejenisnya',Kategori:'C'},
  {Kode:'10771',Judul:'Industri Kopi',Kategori:'C'},
  {Kode:'10772',Judul:'Industri Teh',Kategori:'C'},
  {Kode:'10773',Judul:'Industri Bumbu Masak dan Penyedap Masakan',Kategori:'C'},
  {Kode:'10774',Judul:'Industri Pengolahan Cokelat dan Kembang Gula Berbahan Cokelat',Kategori:'C'},
  {Kode:'10779',Judul:'Industri Produk Makanan Lainnya',Kategori:'C'},
  {Kode:'10800',Judul:'Industri Makanan Hewan',Kategori:'C'},
  {Kode:'11010',Judul:'Industri Minuman Keras',Kategori:'C'},
  {Kode:'11020',Judul:'Industri Minuman Anggur',Kategori:'C'},
  {Kode:'11030',Judul:'Industri Malt dan Minuman Malt (Bir)',Kategori:'C'},
  {Kode:'11041',Judul:'Industri Minuman Ringan',Kategori:'C'},
  {Kode:'11042',Judul:'Industri Minuman Berenergi',Kategori:'C'},
  {Kode:'11043',Judul:'Industri Air Minum dan Air Mineral',Kategori:'C'},
  {Kode:'11049',Judul:'Industri Minuman Tidak Beralkohol Lainnya',Kategori:'C'},
  {Kode:'12011',Judul:'Industri Rokok Kretek',Kategori:'C'},
  {Kode:'12012',Judul:'Industri Rokok Putih',Kategori:'C'},
  {Kode:'12013',Judul:'Industri Rokok Lainnya',Kategori:'C'},
  {Kode:'12090',Judul:'Industri Pengolahan Tembakau Lainnya',Kategori:'C'},
  {Kode:'13111',Judul:'Industri Pemintalan Benang',Kategori:'C'},
  {Kode:'13112',Judul:'Industri Pemintalan Benang Jahit',Kategori:'C'},
  {Kode:'13120',Judul:'Industri Pertenunan (Bukan Pertenunan Karung Goni)',Kategori:'C'},
  {Kode:'13130',Judul:'Industri Penyempurnaan Benang dan Kain',Kategori:'C'},
  {Kode:'13910',Judul:'Industri Kain Rajutan dan Sulaman/Bordiran',Kategori:'C'},
  {Kode:'13921',Judul:'Industri Linen Rumah Tangga',Kategori:'C'},
  {Kode:'13922',Judul:'Industri Karpet dan Permadani',Kategori:'C'},
  {Kode:'13930',Judul:'Industri Tali, Tambang, dan Sejenisnya',Kategori:'C'},
  {Kode:'13941',Judul:'Industri Tekstil Bukan Tenunan (Kain Kempa)',Kategori:'C'},
  {Kode:'13949',Judul:'Industri Tekstil Lainnya',Kategori:'C'},
  {Kode:'13990',Judul:'Industri Kain Rajutan dan Sulaman/Bordiran Lainnya',Kategori:'C'},
  {Kode:'14101',Judul:'Industri Pakaian Jadi (Bukan Penjahitan dan Pembuatan Pakaian Pesanan)',Kategori:'C'},
  {Kode:'14102',Judul:'Industri Perlengkapan Pakaian',Kategori:'C'},
  {Kode:'14200',Judul:'Industri Pakaian Jadi dan Barang dari Kulit Berbulu',Kategori:'C'},
  {Kode:'14301',Judul:'Industri Pakaian Jadi Rajutan dan Sulaman/Bordiran',Kategori:'C'},
  {Kode:'15111',Judul:'Industri Kulit dan Kulit Buatan',Kategori:'C'},
  {Kode:'15112',Judul:'Industri Barang dari Kulit dan Kulit Buatan untuk Keperluan Pribadi',Kategori:'C'},
  {Kode:'15120',Judul:'Industri Tas, Koper, dan Sejenisnya',Kategori:'C'},
  {Kode:'15200',Judul:'Industri Alas Kaki',Kategori:'C'},
  {Kode:'16101',Judul:'Industri Penggergajian dan Pengawetan Kayu, Rotan, Bambu, dan Sejenisnya',Kategori:'C'},
  {Kode:'16102',Judul:'Industri Pengawetan Kayu',Kategori:'C'},
  {Kode:'16211',Judul:'Industri Kayu Lapis',Kategori:'C'},
  {Kode:'16212',Judul:'Industri Kayu Laminasi',Kategori:'C'},
  {Kode:'16219',Judul:'Industri Panel Kayu Lainnya',Kategori:'C'},
  {Kode:'16221',Judul:'Industri Bangunan Prafabrikasi dari Kayu',Kategori:'C'},
  {Kode:'16229',Judul:'Industri Barang Bangunan dari Kayu Lainnya',Kategori:'C'},
  {Kode:'16231',Judul:'Industri Peti Kemas dari Kayu',Kategori:'C'},
  {Kode:'16232',Judul:'Industri Anyaman dari Rotan dan Bambu',Kategori:'C'},
  {Kode:'16239',Judul:'Industri Barang dari Kayu, Rotan, dan Bambu Lainnya',Kategori:'C'},
  {Kode:'16291',Judul:'Industri Barang dari Gabus',Kategori:'C'},
  {Kode:'16292',Judul:'Industri Kerajinan Ukiran Kayu',Kategori:'C'},
  {Kode:'16299',Judul:'Industri Barang dari Kayu Lainnya',Kategori:'C'},
  {Kode:'17011',Judul:'Industri Bubur Kertas (Pulp)',Kategori:'C'},
  {Kode:'17012',Judul:'Industri Kertas dan Papan Kertas (Karton)',Kategori:'C'},
  {Kode:'17021',Judul:'Industri Peti Kemas dari Kertas dan Karton',Kategori:'C'},
  {Kode:'17022',Judul:'Industri Kemasan dari Kertas dan Karton',Kategori:'C'},
  {Kode:'17091',Judul:'Industri Barang dari Kertas dan Karton',Kategori:'C'},
  {Kode:'17099',Judul:'Industri Kertas dan Produk Kertas Lainnya',Kategori:'C'},
  {Kode:'18111',Judul:'Industri Percetakan Umum',Kategori:'C'},
  {Kode:'18112',Judul:'Industri Pencetakan Surat Kabar, Buku, dan Penerbitan Lainnya',Kategori:'C'},
  {Kode:'18120',Judul:'Kegiatan yang Berhubungan dengan Percetakan',Kategori:'C'},
  {Kode:'18200',Judul:'Reproduksi Media Rekaman',Kategori:'C'},
  {Kode:'19100',Judul:'Industri Produk dari Batubara',Kategori:'C'},
  {Kode:'19200',Judul:'Industri Produk Kilang Minyak Bumi',Kategori:'C'},
  {Kode:'20111',Judul:'Industri Bahan Kimia Industri',Kategori:'C'},
  {Kode:'20112',Judul:'Industri Kimia Lainnya',Kategori:'C'},
  {Kode:'20121',Judul:'Industri Pupuk',Kategori:'C'},
  {Kode:'20122',Judul:'Industri Hasil Serangga dan Produk Lainnya',Kategori:'C'},
  {Kode:'20131',Judul:'Industri Plastik dan Karet Sintetis dalam Bentuk Dasar',Kategori:'C'},
  {Kode:'20132',Judul:'Industri Bahan Kimia Dasar Organik',Kategori:'C'},
  {Kode:'20141',Judul:'Industri Cat, Vernis dan Sejenisnya',Kategori:'C'},
  {Kode:'20142',Judul:'Industri Tinta Cetak',Kategori:'C'},
  {Kode:'20151',Judul:'Industri Sabun dan Bahan Pembersih',Kategori:'C'},
  {Kode:'20152',Judul:'Industri Kosmetik',Kategori:'C'},
  {Kode:'20159',Judul:'Industri Parfum dan Kosmetika Lainnya',Kategori:'C'},
  {Kode:'20211',Judul:'Industri Pestisida',Kategori:'C'},
  {Kode:'20219',Judul:'Industri Produk Agrokimia Lainnya',Kategori:'C'},
  {Kode:'20220',Judul:'Industri Bahan Peledak',Kategori:'C'},
  {Kode:'20231',Judul:'Industri Perekat/Lem',Kategori:'C'},
  {Kode:'20232',Judul:'Industri Minyak Atsiri',Kategori:'C'},
  {Kode:'20233',Judul:'Industri Korek Api',Kategori:'C'},
  {Kode:'20239',Judul:'Industri Kimia Dasar Lainnya',Kategori:'C'},
  {Kode:'20291',Judul:'Industri Produk Kimia Lainnya',Kategori:'C'},
  {Kode:'20299',Judul:'Industri Produk Kimia Lainnya Yang Belum Tercakup',Kategori:'C'},
  {Kode:'20301',Judul:'Industri Serat Buatan',Kategori:'C'},
  {Kode:'20302',Judul:'Industri Bahan Kimia Anorganik Dasar',Kategori:'C'},
  {Kode:'21011',Judul:'Industri Bahan Farmasi',Kategori:'C'},
  {Kode:'21012',Judul:'Industri Produk Farmasi',Kategori:'C'},
  {Kode:'21013',Judul:'Industri Obat Tradisional',Kategori:'C'},
  {Kode:'21021',Judul:'Industri Produk Farmasi untuk Hewan',Kategori:'C'},
  {Kode:'21022',Judul:'Industri Bahan Kimia dan Produk Farmasi Lainnya',Kategori:'C'},
  {Kode:'21023',Judul:'Industri Alat Kesehatan dan Kedokteran',Kategori:'C'},
  {Kode:'22111',Judul:'Industri Ban Dalam dan Ban Luar',Kategori:'C'},
  {Kode:'22112',Judul:'Industri Vulkanisir Ban',Kategori:'C'},
  {Kode:'22191',Judul:'Industri Karet untuk Keperluan Industri',Kategori:'C'},
  {Kode:'22192',Judul:'Industri Barang dari Karet Lainnya',Kategori:'C'},
  {Kode:'22199',Judul:'Industri Barang Karet Lainnya',Kategori:'C'},
  {Kode:'22210',Judul:'Industri Barang Plastik untuk Bangunan',Kategori:'C'},
  {Kode:'22220',Judul:'Industri Kemasan Plastik',Kategori:'C'},
  {Kode:'22230',Judul:'Industri Barang Plastik Lainnya',Kategori:'C'},
  {Kode:'22291',Judul:'Industri Produk Plastik Lainnya',Kategori:'C'},
  {Kode:'22299',Judul:'Industri Barang dari Plastik Lainnya',Kategori:'C'},
  {Kode:'23111',Judul:'Industri Kaca Lembaran',Kategori:'C'},
  {Kode:'23112',Judul:'Industri Kaca Pelapis dan Kaca Cermin',Kategori:'C'},
  {Kode:'23119',Judul:'Industri Kaca dan Barang dari Kaca Lainnya',Kategori:'C'},
  {Kode:'23120',Judul:'Industri Barang dari Kaca',Kategori:'C'},
  {Kode:'23210',Judul:'Industri Keramik Refraktori',Kategori:'C'},
  {Kode:'23221',Judul:'Industri Bata Tahan Api',Kategori:'C'},
  {Kode:'23222',Judul:'Industri Bahan Bangunan dari Tanah Liat/Keramik',Kategori:'C'},
  {Kode:'23230',Judul:'Industri Barang Keramik Bukan Tanah Liat Refraktori',Kategori:'C'},
  {Kode:'23240',Judul:'Industri Semen',Kategori:'C'},
  {Kode:'23250',Judul:'Industri Kapur',Kategori:'C'},
  {Kode:'23261',Judul:'Industri Barang dari Semen',Kategori:'C'},
  {Kode:'23262',Judul:'Industri Beton untuk Konstruksi',Kategori:'C'},
  {Kode:'23263',Judul:'Industri Beton Pracetak',Kategori:'C'},
  {Kode:'23269',Judul:'Industri Barang dari Semen dan Kapur Lainnya',Kategori:'C'},
  {Kode:'23910',Judul:'Industri Produk Abrasif',Kategori:'C'},
  {Kode:'23990',Judul:'Industri Barang Galian Bukan Logam Lainnya',Kategori:'C'},
  {Kode:'24101',Judul:'Industri Besi dan Baja Dasar (Iron and Steel Making)',Kategori:'C'},
  {Kode:'24102',Judul:'Industri Penggilingan Baja (Steel Rolling)',Kategori:'C'},
  {Kode:'24103',Judul:'Industri Pipa dan Sambungan Pipa dari Baja',Kategori:'C'},
  {Kode:'24200',Judul:'Industri Logam Mulia dan Logam Langka',Kategori:'C'},
  {Kode:'24310',Judul:'Industri Pengecoran Besi dan Baja',Kategori:'C'},
  {Kode:'24320',Judul:'Industri Pengecoran Logam Bukan Besi',Kategori:'C'},
  {Kode:'25111',Judul:'Industri Penempaan, Pengepresan, dan Penggulungan Logam',Kategori:'C'},
  {Kode:'25112',Judul:'Industri Barang dari Logam Bukan Aluminium',Kategori:'C'},
  {Kode:'25113',Judul:'Industri Barang dari Logam Aluminium',Kategori:'C'},
  {Kode:'25120',Judul:'Industri Alat Pertanian',Kategori:'C'},
  {Kode:'25130',Judul:'Industri Tangki, Tangki Penampungan, dan Kontainer dari Logam',Kategori:'C'},
  {Kode:'25140',Judul:'Industri Senjata dan Amunisi',Kategori:'C'},
  {Kode:'25150',Judul:'Industri Peralatan Memasak dan Dapur dari Logam',Kategori:'C'},
  {Kode:'25910',Judul:'Industri Mesin Pertanian dan Kehutanan',Kategori:'C'},
  {Kode:'25920',Judul:'Industri Perkakas',Kategori:'C'},
  {Kode:'25931',Judul:'Industri Pengolahan Logam Dasar Mulia',Kategori:'C'},
  {Kode:'25939',Judul:'Industri Perlengkapan Logam untuk Bangunan Lainnya',Kategori:'C'},
  {Kode:'25940',Judul:'Industri Barang Logam Hasil Tempa, Press dan Gulung',Kategori:'C'},
  {Kode:'25990',Judul:'Industri Barang Logam Lainnya',Kategori:'C'},
  {Kode:'26110',Judul:'Industri Komponen Elektronika',Kategori:'C'},
  {Kode:'26120',Judul:'Industri Papan Sirkuit Elektronika',Kategori:'C'},
  {Kode:'26210',Judul:'Industri Komputer dan Perlengkapannya',Kategori:'C'},
  {Kode:'26220',Judul:'Industri Mesin Kantor Lainnya',Kategori:'C'},
  {Kode:'26310',Judul:'Industri Peralatan Telekomunikasi',Kategori:'C'},
  {Kode:'26320',Judul:'Industri Radio dan Televisi',Kategori:'C'},
  {Kode:'26400',Judul:'Industri Produk Elektronika Konsumen',Kategori:'C'},
  {Kode:'26510',Judul:'Industri Alat Ukur, Uji, Navigasi dan Kontrol',Kategori:'C'},
  {Kode:'26520',Judul:'Industri Jam dan Sejenisnya',Kategori:'C'},
  {Kode:'26600',Judul:'Industri Peralatan Iradiasi, Elektromedikal, dan Elektroterapi',Kategori:'C'},
  {Kode:'26700',Judul:'Industri Instrumen Optik dan Fotografi',Kategori:'C'},
  {Kode:'26800',Judul:'Industri Media Magnetik dan Media Optik',Kategori:'C'},
  {Kode:'26900',Judul:'Industri Komponen dan Produk Elektronika Lainnya',Kategori:'C'},
  {Kode:'27101',Judul:'Industri Motor Listrik, Generator, Transformator, dan Peralatan Pengontrol dan Pendistribusian Listrik',Kategori:'C'},
  {Kode:'27102',Judul:'Industri Mesin Listrik Lainnya',Kategori:'C'},
  {Kode:'27200',Judul:'Industri Baterai dan Akumulator',Kategori:'C'},
  {Kode:'27310',Judul:'Industri Kabel Serat Optik',Kategori:'C'},
  {Kode:'27320',Judul:'Industri Kabel dan Kawat Listrik',Kategori:'C'},
  {Kode:'27400',Judul:'Industri Peralatan Listrik untuk Keperluan Rumah Tangga',Kategori:'C'},
  {Kode:'27500',Judul:'Industri Peralatan Rumah Tangga dengan Bukan Listrik',Kategori:'C'},
  {Kode:'27900',Judul:'Industri Peralatan Listrik Lainnya',Kategori:'C'},
  {Kode:'28110',Judul:'Industri Mesin untuk Keperluan Umum',Kategori:'C'},
  {Kode:'28120',Judul:'Industri Mesin Fluida',Kategori:'C'},
  {Kode:'28130',Judul:'Industri Pompa, Kompresor, Kran dan Katup',Kategori:'C'},
  {Kode:'28140',Judul:'Industri Bantalan, Roda Gigi, dan Elemen Penggerak Mesin Lainnya',Kategori:'C'},
  {Kode:'28150',Judul:'Industri Tungku dan Pemanas Industri',Kategori:'C'},
  {Kode:'28160',Judul:'Industri Peralatan Pengangkat dan Pemindah',Kategori:'C'},
  {Kode:'28170',Judul:'Industri Mesin Kantor, Akuntansi, dan Komputer',Kategori:'C'},
  {Kode:'28180',Judul:'Industri Peralatan Tenaga dan Pemindahan Daya',Kategori:'C'},
  {Kode:'28190',Judul:'Industri Mesin Untuk Keperluan Umum Lainnya',Kategori:'C'},
  {Kode:'28210',Judul:'Industri Mesin Pertanian dan Kehutanan',Kategori:'C'},
  {Kode:'28220',Judul:'Industri Mesin Untuk Pembentukan Logam',Kategori:'C'},
  {Kode:'28230',Judul:'Industri Mesin Metalurgi',Kategori:'C'},
  {Kode:'28240',Judul:'Industri Mesin Pertambangan, Penggalian, dan Konstruksi',Kategori:'C'},
  {Kode:'28250',Judul:'Industri Mesin Pengolahan Makanan, Minuman, dan Tembakau',Kategori:'C'},
  {Kode:'28260',Judul:'Industri Mesin Tekstil, Pakaian Jadi, dan Kulit',Kategori:'C'},
  {Kode:'28290',Judul:'Industri Mesin Untuk Keperluan Khusus Lainnya',Kategori:'C'},
  {Kode:'28990',Judul:'Industri Mesin Keperluan Khusus Lainnya',Kategori:'C'},
  {Kode:'29100',Judul:'Industri Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'C'},
  {Kode:'29200',Judul:'Industri Karoseri Kendaraan Bermotor, Trailer dan Semi Trailer',Kategori:'C'},
  {Kode:'29300',Judul:'Industri Suku Cadang dan Aksesori Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'C'},
  {Kode:'30111',Judul:'Industri Kapal dan Perahu',Kategori:'C'},
  {Kode:'30112',Judul:'Industri Bangunan Lepas Pantai',Kategori:'C'},
  {Kode:'30120',Judul:'Industri Bangunan Kapal untuk Olah Raga dan Rekreasi',Kategori:'C'},
  {Kode:'30200',Judul:'Industri Kereta Api dan Komponennya',Kategori:'C'},
  {Kode:'30300',Judul:'Industri Pesawat Terbang dan Perlengkapannya',Kategori:'C'},
  {Kode:'30400',Judul:'Industri Kendaraan Militer',Kategori:'C'},
  {Kode:'30911',Judul:'Industri Sepeda Motor',Kategori:'C'},
  {Kode:'30912',Judul:'Industri Komponen dan Perlengkapan Sepeda Motor',Kategori:'C'},
  {Kode:'30920',Judul:'Industri Sepeda dan Kursi Roda',Kategori:'C'},
  {Kode:'30990',Judul:'Industri Alat Angkutan Lainnya',Kategori:'C'},
  {Kode:'31001',Judul:'Industri Furnitur dari Kayu',Kategori:'C'},
  {Kode:'31002',Judul:'Industri Furnitur dari Rotan dan Bambu',Kategori:'C'},
  {Kode:'31003',Judul:'Industri Furnitur dari Plastik',Kategori:'C'},
  {Kode:'31004',Judul:'Industri Furnitur dari Logam',Kategori:'C'},
  {Kode:'31009',Judul:'Industri Furnitur Lainnya',Kategori:'C'},
  {Kode:'32011',Judul:'Industri Perhiasan dan Barang Berharga',Kategori:'C'},
  {Kode:'32012',Judul:'Industri Perhiasan Bukan Logam Mulia',Kategori:'C'},
  {Kode:'32020',Judul:'Industri Alat Musik',Kategori:'C'},
  {Kode:'32030',Judul:'Industri Alat Olahraga',Kategori:'C'},
  {Kode:'32040',Judul:'Industri Mainan Anak-Anak',Kategori:'C'},
  {Kode:'32050',Judul:'Industri Alat Tulis dan Gambar',Kategori:'C'},
  {Kode:'32090',Judul:'Industri Pengolahan Lainnya',Kategori:'C'},
  {Kode:'33111',Judul:'Reparasi Produk Logam Fabrikasi',Kategori:'C'},
  {Kode:'33112',Judul:'Reparasi Mesin',Kategori:'C'},
  {Kode:'33113',Judul:'Reparasi Peralatan Elektronik dan Optik',Kategori:'C'},
  {Kode:'33114',Judul:'Reparasi Peralatan Listrik',Kategori:'C'},
  {Kode:'33115',Judul:'Reparasi Kapal dan Perahu',Kategori:'C'},
  {Kode:'33116',Judul:'Reparasi Kereta Api',Kategori:'C'},
  {Kode:'33117',Judul:'Reparasi Pesawat Terbang',Kategori:'C'},
  {Kode:'33119',Judul:'Reparasi Alat Angkutan Lainnya',Kategori:'C'},
  {Kode:'33120',Judul:'Instalasi Mesin dan Peralatan Industri',Kategori:'C'},
  {Kode:'33200',Judul:'Instalasi Industri',Kategori:'C'},
  // ===== D: PENGADAAN LISTRIK DAN GAS =====
  {Kode:'35101',Judul:'Pembangkitan Tenaga Listrik',Kategori:'D'},
  {Kode:'35102',Judul:'Transmisi Tenaga Listrik',Kategori:'D'},
  {Kode:'35103',Judul:'Distribusi Tenaga Listrik',Kategori:'D'},
  {Kode:'35104',Judul:'Perdagangan Tenaga Listrik',Kategori:'D'},
  {Kode:'35201',Judul:'Produksi Gas',Kategori:'D'},
  {Kode:'35202',Judul:'Distribusi Gas Melalui Pipa',Kategori:'D'},
  {Kode:'35203',Judul:'Perdagangan Gas',Kategori:'D'},
  {Kode:'35300',Judul:'Pengadaan Uap, Air Panas, Udara Dingin dan Produksi Es',Kategori:'D'},
  // ===== E: PENGADAAN AIR, PENGELOLAAN SAMPAH =====
  {Kode:'36001',Judul:'Pengumpulan, Pengolahan dan Penyaluran Air',Kategori:'E'},
  {Kode:'36002',Judul:'Pengoperasian Fasilitas Pengairan',Kategori:'E'},
  {Kode:'37000',Judul:'Pengelolaan Air Limbah',Kategori:'E'},
  {Kode:'38110',Judul:'Pengumpulan Sampah Tidak Berbahaya',Kategori:'E'},
  {Kode:'38120',Judul:'Pengumpulan Sampah Berbahaya',Kategori:'E'},
  {Kode:'38210',Judul:'Pengolahan dan Pembuangan Sampah Tidak Berbahaya',Kategori:'E'},
  {Kode:'38220',Judul:'Pengolahan dan Pembuangan Sampah Berbahaya',Kategori:'E'},
  {Kode:'38301',Judul:'Daur Ulang Serpihan Logam',Kategori:'E'},
  {Kode:'38302',Judul:'Daur Ulang Non Logam',Kategori:'E'},
  {Kode:'39000',Judul:'Remediasi dan Pengelolaan Sampah Lainnya',Kategori:'E'},
  // ===== F: KONSTRUKSI =====
  {Kode:'41011',Judul:'Konstruksi Gedung Hunian',Kategori:'F'},
  {Kode:'41012',Judul:'Konstruksi Gedung Perkantoran',Kategori:'F'},
  {Kode:'41013',Judul:'Konstruksi Gedung Industri',Kategori:'F'},
  {Kode:'41014',Judul:'Konstruksi Gedung Perbelanjaan',Kategori:'F'},
  {Kode:'41015',Judul:'Konstruksi Gedung Penginapan',Kategori:'F'},
  {Kode:'41016',Judul:'Konstruksi Gedung Tempat Hiburan dan Olahraga',Kategori:'F'},
  {Kode:'41017',Judul:'Konstruksi Gedung Pendidikan',Kategori:'F'},
  {Kode:'41018',Judul:'Konstruksi Gedung Kesehatan',Kategori:'F'},
  {Kode:'41019',Judul:'Konstruksi Gedung Lainnya',Kategori:'F'},
  {Kode:'41020',Judul:'Konstruksi Bangunan Sipil',Kategori:'F'},
  {Kode:'42101',Judul:'Konstruksi Jalan Raya (Bukan Jalan Layang) dan Jembatan',Kategori:'F'},
  {Kode:'42102',Judul:'Konstruksi Jalan Rel Kereta Api',Kategori:'F'},
  {Kode:'42103',Judul:'Konstruksi Jalan Layang',Kategori:'F'},
  {Kode:'42104',Judul:'Konstruksi Jalan Bawah Tanah',Kategori:'F'},
  {Kode:'42201',Judul:'Konstruksi Saluran Air dan Drainase',Kategori:'F'},
  {Kode:'42202',Judul:'Konstruksi Bangunan Pengolahan Air Bersih dan Air Limbah',Kategori:'F'},
  {Kode:'42203',Judul:'Konstruksi Bangunan Elektrikal',Kategori:'F'},
  {Kode:'42204',Judul:'Konstruksi Bangunan Telekomunikasi',Kategori:'F'},
  {Kode:'42901',Judul:'Konstruksi Bangunan Pelabuhan',Kategori:'F'},
  {Kode:'42902',Judul:'Konstruksi Bangunan Pengolahan Industri',Kategori:'F'},
  {Kode:'42909',Judul:'Konstruksi Bangunan Sipil Lainnya',Kategori:'F'},
  {Kode:'43111',Judul:'Pembongkaran Bangunan',Kategori:'F'},
  {Kode:'43112',Judul:'Penyiapan Lahan untuk Konstruksi',Kategori:'F'},
  {Kode:'43121',Judul:'Konstruksi Khusus Penggalian',Kategori:'F'},
  {Kode:'43122',Judul:'Konstruksi Pondasi Bangunan',Kategori:'F'},
  {Kode:'43211',Judul:'Instalasi Listrik',Kategori:'F'},
  {Kode:'43212',Judul:'Instalasi Minyak Gas',Kategori:'F'},
  {Kode:'43213',Judul:'Instalasi Air dan Sanitasi',Kategori:'F'},
  {Kode:'43214',Judul:'Instalasi Sistem Pendingin dan Pemanas Udara',Kategori:'F'},
  {Kode:'43219',Judul:'Instalasi Mekanikal dan Elektrikal Lainnya',Kategori:'F'},
  {Kode:'43221',Judul:'Pemasangan Kaca',Kategori:'F'},
  {Kode:'43222',Judul:'Pemasangan Rangka Atap',Kategori:'F'},
  {Kode:'43223',Judul:'Pemasangan Pintu, Jendela, dan Sejenisnya',Kategori:'F'},
  {Kode:'43224',Judul:'Pemasangan Plafon',Kategori:'F'},
  {Kode:'43290',Judul:'Konstruksi Bangunan Lainnya',Kategori:'F'},
  {Kode:'43301',Judul:'Pemasangan Tegel dan Lantai dari Keramik',Kategori:'F'},
  {Kode:'43302',Judul:'Pengecatan Bangunan',Kategori:'F'},
  {Kode:'43303',Judul:'Pemasangan Karpet dan Penutup Lantai Lainnya',Kategori:'F'},
  {Kode:'43309',Judul:'Konstruksi Penyelesaian Bangunan Lainnya',Kategori:'F'},
  {Kode:'43901',Judul:'Konstruksi Khusus Lainnya',Kategori:'F'},
  {Kode:'43902',Judul:'Persewaan Alat Konstruksi dengan Operator',Kategori:'F'},
  {Kode:'43909',Judul:'Konstruksi Lainnya',Kategori:'F'},
  // ===== G: PERDAGANGAN BESAR DAN ECERAN =====
  {Kode:'45101',Judul:'Perdagangan Besar Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'G'},
  {Kode:'45102',Judul:'Perdagangan Eceran Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'G'},
  {Kode:'45201',Judul:'Reparasi Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'G'},
  {Kode:'45202',Judul:'Perawatan Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'G'},
  {Kode:'45301',Judul:'Perdagangan Besar Suku Cadang dan Aksesori Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'G'},
  {Kode:'45302',Judul:'Perdagangan Eceran Suku Cadang dan Aksesori Kendaraan Bermotor Roda Empat atau Lebih',Kategori:'G'},
  {Kode:'45401',Judul:'Perdagangan Besar Sepeda Motor Baru',Kategori:'G'},
  {Kode:'45402',Judul:'Perdagangan Eceran Sepeda Motor Baru',Kategori:'G'},
  {Kode:'45403',Judul:'Perdagangan Sepeda Motor Bekas',Kategori:'G'},
  {Kode:'45404',Judul:'Reparasi Sepeda Motor dan Perdagangan Suku Cadang',Kategori:'G'},
  {Kode:'46100',Judul:'Perdagangan Besar atas Dasar Balas Jasa atau Kontrak',Kategori:'G'},
  {Kode:'46211',Judul:'Perdagangan Besar Bahan Pertanian',Kategori:'G'},
  {Kode:'46212',Judul:'Perdagangan Besar Hasil Perikanan',Kategori:'G'},
  {Kode:'46213',Judul:'Perdagangan Besar Hasil Kehutanan',Kategori:'G'},
  {Kode:'46214',Judul:'Perdagangan Besar Hasil Perkebunan',Kategori:'G'},
  {Kode:'46215',Judul:'Perdagangan Besar Binatang Hidup',Kategori:'G'},
  {Kode:'46219',Judul:'Perdagangan Besar Bahan Pertanian Lainnya',Kategori:'G'},
  {Kode:'46220',Judul:'Perdagangan Besar Makanan, Minuman dan Tembakau',Kategori:'G'},
  {Kode:'46230',Judul:'Perdagangan Besar Bahan Baku untuk Industri',Kategori:'G'},
  {Kode:'46310',Judul:'Perdagangan Besar Berbagai Macam Barang',Kategori:'G'},
  {Kode:'46320',Judul:'Perdagangan Besar Bahan Makanan dan Minuman untuk Rumah Tangga',Kategori:'G'},
  {Kode:'46331',Judul:'Perdagangan Besar Rokok dan Tembakau',Kategori:'G'},
  {Kode:'46332',Judul:'Perdagangan Besar Bahan Makanan Olahan',Kategori:'G'},
  {Kode:'46339',Judul:'Perdagangan Besar Makanan dan Minuman Lainnya',Kategori:'G'},
  {Kode:'46410',Judul:'Perdagangan Besar Tekstil',Kategori:'G'},
  {Kode:'46420',Judul:'Perdagangan Besar Pakaian dan Perlengkapannya',Kategori:'G'},
  {Kode:'46430',Judul:'Perdagangan Besar Peralatan Rumah Tangga',Kategori:'G'},
  {Kode:'46441',Judul:'Perdagangan Besar Komputer dan Perlengkapannya',Kategori:'G'},
  {Kode:'46442',Judul:'Perdagangan Besar Peralatan Elektronik',Kategori:'G'},
  {Kode:'46443',Judul:'Perdagangan Besar Telepon',Kategori:'G'},
  {Kode:'46491',Judul:'Perdagangan Besar Alat Tulis',Kategori:'G'},
  {Kode:'46492',Judul:'Perdagangan Besar Buku',Kategori:'G'},
  {Kode:'46493',Judul:'Perdagangan Besar Mainan Anak',Kategori:'G'},
  {Kode:'46499',Judul:'Perdagangan Besar Barang Konsumsi Lainnya',Kategori:'G'},
  {Kode:'46510',Judul:'Perdagangan Besar Komputer dan Perlengkapan Komputer',Kategori:'G'},
  {Kode:'46520',Judul:'Perdagangan Besar Elektronik dan Telekomunikasi',Kategori:'G'},
  {Kode:'46590',Judul:'Perdagangan Besar Mesin, Peralatan dan Perlengkapan Lainnya',Kategori:'G'},
  {Kode:'46610',Judul:'Perdagangan Besar Bahan Bakar Padat, Cair, dan Gas',Kategori:'G'},
  {Kode:'46620',Judul:'Perdagangan Besar Logam dan Bijih Logam',Kategori:'G'},
  {Kode:'46630',Judul:'Perdagangan Besar Bahan dan Perlengkapan Bangunan',Kategori:'G'},
  {Kode:'46691',Judul:'Perdagangan Besar Pupuk dan Pestisida',Kategori:'G'},
  {Kode:'46699',Judul:'Perdagangan Besar Bahan Industri Lainnya',Kategori:'G'},
  {Kode:'46701',Judul:'Perdagangan Besar Limbah dan Sampah',Kategori:'G'},
  {Kode:'46709',Judul:'Perdagangan Besar Lainnya',Kategori:'G'},
  {Kode:'47111',Judul:'Perdagangan Eceran Berbagai Macam Barang (Supermarket/Hypermarket)',Kategori:'G'},
  {Kode:'47112',Judul:'Perdagangan Eceran Berbagai Macam Barang (Minimarket)',Kategori:'G'},
  {Kode:'47113',Judul:'Perdagangan Eceran Berbagai Macam Barang Lainnya',Kategori:'G'},
  {Kode:'47121',Judul:'Perdagangan Eceran Buah-Buahan dan Sayuran',Kategori:'G'},
  {Kode:'47122',Judul:'Perdagangan Eceran Hasil Pertanian Lainnya',Kategori:'G'},
  {Kode:'47211',Judul:'Perdagangan Eceran Daging dan Ayam',Kategori:'G'},
  {Kode:'47212',Judul:'Perdagangan Eceran Ikan',Kategori:'G'},
  {Kode:'47213',Judul:'Perdagangan Eceran Susu dan Telur',Kategori:'G'},
  {Kode:'47214',Judul:'Perdagangan Eceran Bahan Makanan Lainnya',Kategori:'G'},
  {Kode:'47221',Judul:'Perdagangan Eceran Minuman Beralkohol',Kategori:'G'},
  {Kode:'47222',Judul:'Perdagangan Eceran Minuman Tidak Beralkohol',Kategori:'G'},
  {Kode:'47230',Judul:'Perdagangan Eceran Tembakau dan Rokok',Kategori:'G'},
  {Kode:'47311',Judul:'Perdagangan Eceran Bahan Bakar Kendaraan di SPBU',Kategori:'G'},
  {Kode:'47312',Judul:'Perdagangan Eceran Bahan Bakar Kendaraan Bukan di SPBU',Kategori:'G'},
  {Kode:'47319',Judul:'Perdagangan Eceran Bahan Bakar Kendaraan Lainnya',Kategori:'G'},
  {Kode:'47411',Judul:'Perdagangan Eceran Komputer dan Perlengkapannya',Kategori:'G'},
  {Kode:'47412',Judul:'Perdagangan Eceran Peralatan Elektronik',Kategori:'G'},
  {Kode:'47413',Judul:'Perdagangan Eceran Telepon dan Perlengkapannya',Kategori:'G'},
  {Kode:'47420',Judul:'Perdagangan Eceran Peralatan Audio dan Video',Kategori:'G'},
  {Kode:'47510',Judul:'Perdagangan Eceran Tekstil',Kategori:'G'},
  {Kode:'47521',Judul:'Perdagangan Eceran Bahan Bangunan',Kategori:'G'},
  {Kode:'47522',Judul:'Perdagangan Eceran Peralatan Bangunan dan Pertukangan',Kategori:'G'},
  {Kode:'47530',Judul:'Perdagangan Eceran Karpet, Permadani dan Penutup Dinding dan Lantai',Kategori:'G'},
  {Kode:'47591',Judul:'Perdagangan Eceran Furnitur',Kategori:'G'},
  {Kode:'47592',Judul:'Perdagangan Eceran Peralatan Rumah Tangga',Kategori:'G'},
  {Kode:'47593',Judul:'Perdagangan Eceran Barang Kerajinan',Kategori:'G'},
  {Kode:'47594',Judul:'Perdagangan Eceran Musik, Olahraga dan Mainan',Kategori:'G'},
  {Kode:'47596',Judul:'Perdagangan Eceran Alat Tulis dan Kantor',Kategori:'G'},
  {Kode:'47599',Judul:'Perdagangan Eceran Perlengkapan Rumah Tangga Lainnya',Kategori:'G'},
  {Kode:'47611',Judul:'Perdagangan Eceran Buku',Kategori:'G'},
  {Kode:'47612',Judul:'Perdagangan Eceran Surat Kabar dan Majalah',Kategori:'G'},
  {Kode:'47620',Judul:'Perdagangan Eceran Rekaman Musik dan Video',Kategori:'G'},
  {Kode:'47630',Judul:'Perdagangan Eceran Alat Olahraga',Kategori:'G'},
  {Kode:'47640',Judul:'Perdagangan Eceran Alat Permainan',Kategori:'G'},
  {Kode:'47711',Judul:'Perdagangan Eceran Pakaian',Kategori:'G'},
  {Kode:'47712',Judul:'Perdagangan Eceran Pakaian Anak',Kategori:'G'},
  {Kode:'47721',Judul:'Perdagangan Eceran Alas Kaki',Kategori:'G'},
  {Kode:'47722',Judul:'Perdagangan Eceran Tas dan Aksesori',Kategori:'G'},
  {Kode:'47730',Judul:'Perdagangan Eceran Farmasi dan Obat Tradisional',Kategori:'G'},
  {Kode:'47740',Judul:'Perdagangan Eceran Alat Kesehatan dan Kosmetik',Kategori:'G'},
  {Kode:'47751',Judul:'Perdagangan Eceran Bunga',Kategori:'G'},
  {Kode:'47752',Judul:'Perdagangan Eceran Hewan Peliharaan',Kategori:'G'},
  {Kode:'47759',Judul:'Perdagangan Eceran Barang Lainnya',Kategori:'G'},
  {Kode:'47761',Judul:'Perdagangan Eceran Perhiasan dan Jam Tangan',Kategori:'G'},
  {Kode:'47762',Judul:'Perdagangan Eceran Souvenir, Kerajinan dan Barang Seni',Kategori:'G'},
  {Kode:'47763',Judul:'Perdagangan Eceran Optik',Kategori:'G'},
  {Kode:'47769',Judul:'Perdagangan Eceran Khusus Lainnya',Kategori:'G'},
  {Kode:'47771',Judul:'Perdagangan Eceran Melalui Media',Kategori:'G'},
  {Kode:'47772',Judul:'Perdagangan Eceran Melalui Internet',Kategori:'G'},
  {Kode:'47781',Judul:'Perdagangan Eceran Barang Bekas',Kategori:'G'},
  {Kode:'47791',Judul:'Perdagangan Eceran Kaki Lima dan Los Pasar',Kategori:'G'},
  {Kode:'47799',Judul:'Perdagangan Eceran Keliling Lainnya',Kategori:'G'},
  // ===== H: TRANSPORTASI DAN PERGUDANGAN =====
  {Kode:'49110',Judul:'Angkutan Kereta Api untuk Penumpang',Kategori:'H'},
  {Kode:'49120',Judul:'Angkutan Kereta Api untuk Barang',Kategori:'H'},
  {Kode:'49211',Judul:'Angkutan Bus Umum Antar Kota Antar Provinsi (AKAP)',Kategori:'H'},
  {Kode:'49212',Judul:'Angkutan Bus Umum Antar Kota Dalam Provinsi (AKDP)',Kategori:'H'},
  {Kode:'49213',Judul:'Angkutan Bus Perkotaan',Kategori:'H'},
  {Kode:'49214',Judul:'Angkutan Pedesaan',Kategori:'H'},
  {Kode:'49215',Judul:'Angkutan Bus Pariwisata',Kategori:'H'},
  {Kode:'49219',Judul:'Angkutan Bus Lainnya',Kategori:'H'},
  {Kode:'49221',Judul:'Angkutan Taksi',Kategori:'H'},
  {Kode:'49222',Judul:'Angkutan Sewa dengan Pengemudi',Kategori:'H'},
  {Kode:'49223',Judul:'Angkutan Bermotor Berbasis Aplikasi',Kategori:'H'},
  {Kode:'49229',Judul:'Angkutan Penumpang Tidak dalam Trayek Lainnya',Kategori:'H'},
  {Kode:'49231',Judul:'Angkutan Barang Umum',Kategori:'H'},
  {Kode:'49232',Judul:'Angkutan Barang Khusus',Kategori:'H'},
  {Kode:'49233',Judul:'Angkutan Barang Berbahaya',Kategori:'H'},
  {Kode:'49239',Judul:'Angkutan Barang Lainnya',Kategori:'H'},
  {Kode:'49300',Judul:'Angkutan Melalui Saluran Pipa',Kategori:'H'},
  {Kode:'50111',Judul:'Angkutan Laut Dalam Negeri untuk Penumpang Liner',Kategori:'H'},
  {Kode:'50112',Judul:'Angkutan Laut Dalam Negeri untuk Penumpang Tramper',Kategori:'H'},
  {Kode:'50113',Judul:'Angkutan Laut Dalam Negeri untuk Penumpang Perintis',Kategori:'H'},
  {Kode:'50121',Judul:'Angkutan Laut Dalam Negeri untuk Barang Liner',Kategori:'H'},
  {Kode:'50122',Judul:'Angkutan Laut Dalam Negeri untuk Barang Tramper',Kategori:'H'},
  {Kode:'50123',Judul:'Angkutan Laut Dalam Negeri untuk Barang Khusus',Kategori:'H'},
  {Kode:'50131',Judul:'Angkutan Laut Luar Negeri untuk Penumpang',Kategori:'H'},
  {Kode:'50141',Judul:'Angkutan Laut Luar Negeri untuk Barang',Kategori:'H'},
  {Kode:'50211',Judul:'Angkutan Sungai dan Danau untuk Penumpang',Kategori:'H'},
  {Kode:'50212',Judul:'Angkutan Sungai dan Danau untuk Barang',Kategori:'H'},
  {Kode:'50221',Judul:'Angkutan Penyeberangan Dalam Negeri untuk Penumpang',Kategori:'H'},
  {Kode:'50222',Judul:'Angkutan Penyeberangan Dalam Negeri untuk Barang',Kategori:'H'},
  {Kode:'51101',Judul:'Angkutan Udara Dalam Negeri untuk Penumpang',Kategori:'H'},
  {Kode:'51102',Judul:'Angkutan Udara Dalam Negeri untuk Barang',Kategori:'H'},
  {Kode:'51201',Judul:'Angkutan Udara Luar Negeri untuk Penumpang',Kategori:'H'},
  {Kode:'51202',Judul:'Angkutan Udara Luar Negeri untuk Barang',Kategori:'H'},
  {Kode:'52101',Judul:'Pergudangan',Kategori:'H'},
  {Kode:'52102',Judul:'Jasa Penyimpanan Dingin (Cold Storage)',Kategori:'H'},
  {Kode:'52210',Judul:'Jasa Penunjang Angkutan Darat',Kategori:'H'},
  {Kode:'52221',Judul:'Jasa Pelabuhan',Kategori:'H'},
  {Kode:'52222',Judul:'Jasa Penunjang Angkutan Sungai, Danau dan Penyeberangan',Kategori:'H'},
  {Kode:'52230',Judul:'Jasa Penunjang Angkutan Udara',Kategori:'H'},
  {Kode:'52291',Judul:'Jasa Ekspedisi',Kategori:'H'},
  {Kode:'52292',Judul:'Jasa Forwarding',Kategori:'H'},
  {Kode:'52299',Judul:'Jasa Penunjang Angkutan Lainnya',Kategori:'H'},
  {Kode:'53100',Judul:'Pos Nasional',Kategori:'H'},
  {Kode:'53200',Judul:'Kurir',Kategori:'H'},
  // ===== I: PENYEDIAAN AKOMODASI DAN MAKAN MINUM =====
  {Kode:'55110',Judul:'Hotel Bintang',Kategori:'I'},
  {Kode:'55120',Judul:'Hotel Melati',Kategori:'I'},
  {Kode:'55130',Judul:'Pondok Wisata',Kategori:'I'},
  {Kode:'55190',Judul:'Penyediaan Akomodasi Jangka Pendek Lainnya',Kategori:'I'},
  {Kode:'55210',Judul:'Penyediaan Akomodasi Jangka Panjang (Kos-Kosan)',Kategori:'I'},
  {Kode:'55220',Judul:'Penyediaan Akomodasi Perkemahan',Kategori:'I'},
  {Kode:'55230',Judul:'Penyediaan Tempat Parkir Karavan',Kategori:'I'},
  {Kode:'55900',Judul:'Penyediaan Akomodasi Lainnya',Kategori:'I'},
  {Kode:'56101',Judul:'Restoran',Kategori:'I'},
  {Kode:'56102',Judul:'Warung Makan dan Sejenisnya',Kategori:'I'},
  {Kode:'56103',Judul:'Rumah Makan Masakan Jadi',Kategori:'I'},
  {Kode:'56104',Judul:'Penyediaan Makanan Jajanan Keliling',Kategori:'I'},
  {Kode:'56109',Judul:'Penyediaan Makanan Lainnya',Kategori:'I'},
  {Kode:'56211',Judul:'Jasa Boga untuk Suatu Event Tertentu (Event Catering)',Kategori:'I'},
  {Kode:'56212',Judul:'Penyediaan Makanan oleh Jasa Boga (Katering)',Kategori:'I'},
  {Kode:'56219',Judul:'Penyediaan Makanan Lainnya',Kategori:'I'},
  {Kode:'56301',Judul:'Bar',Kategori:'I'},
  {Kode:'56302',Judul:'Kafe dan Kedai Kopi',Kategori:'I'},
  {Kode:'56303',Judul:'Pub dan Diskotek',Kategori:'I'},
  {Kode:'56309',Judul:'Penyediaan Minuman Lainnya',Kategori:'I'},
  // ===== J: INFORMASI DAN KOMUNIKASI =====
  {Kode:'58111',Judul:'Penerbitan Buku',Kategori:'J'},
  {Kode:'58112',Judul:'Penerbitan Kamus dan Ensiklopedia',Kategori:'J'},
  {Kode:'58113',Judul:'Penerbitan Buku Pelajaran',Kategori:'J'},
  {Kode:'58119',Judul:'Penerbitan Buku Lainnya',Kategori:'J'},
  {Kode:'58120',Judul:'Penerbitan Buku Panduan Telepon dan Direktori',Kategori:'J'},
  {Kode:'58130',Judul:'Penerbitan Surat Kabar, Jurnal dan Majalah',Kategori:'J'},
  {Kode:'58190',Judul:'Penerbitan Lainnya',Kategori:'J'},
  {Kode:'58200',Judul:'Penerbitan Piranti Lunak (Software)',Kategori:'J'},
  {Kode:'59110',Judul:'Produksi Gambar Bergerak, Video dan Program Televisi',Kategori:'J'},
  {Kode:'59120',Judul:'Pasca Produksi Gambar Bergerak, Video dan Program Televisi',Kategori:'J'},
  {Kode:'59130',Judul:'Distribusi Gambar Bergerak, Video dan Program Televisi',Kategori:'J'},
  {Kode:'59140',Judul:'Pertunjukan Gambar Bergerak',Kategori:'J'},
  {Kode:'59200',Judul:'Perekaman Suara dan Penerbitan Musik',Kategori:'J'},
  {Kode:'60100',Judul:'Penyiaran Radio',Kategori:'J'},
  {Kode:'60200',Judul:'Penyiaran Televisi dan Swasta Melalui Satelit',Kategori:'J'},
  {Kode:'61100',Judul:'Aktivitas Telekomunikasi dengan Kabel',Kategori:'J'},
  {Kode:'61200',Judul:'Aktivitas Telekomunikasi Tanpa Kabel',Kategori:'J'},
  {Kode:'61300',Judul:'Aktivitas Telekomunikasi Satelit',Kategori:'J'},
  {Kode:'61900',Judul:'Aktivitas Telekomunikasi Lainnya',Kategori:'J'},
  {Kode:'62011',Judul:'Aktivitas Pemrograman Komputer',Kategori:'J'},
  {Kode:'62012',Judul:'Pengembangan Aplikasi Perangkat Lunak',Kategori:'J'},
  {Kode:'62013',Judul:'Pengembangan Sistem Informasi',Kategori:'J'},
  {Kode:'62021',Judul:'Aktivitas Konsultasi Komputer',Kategori:'J'},
  {Kode:'62022',Judul:'Aktivitas Konsultasi Teknologi Informasi',Kategori:'J'},
  {Kode:'62090',Judul:'Aktivitas Teknologi Informasi dan Jasa Komputer Lainnya',Kategori:'J'},
  {Kode:'63111',Judul:'Aktivitas Pengolahan Data',Kategori:'J'},
  {Kode:'63112',Judul:'Penyediaan Hosting dan Jasa yang Berhubungan',Kategori:'J'},
  {Kode:'63113',Judul:'Portal Web dan Platform Digital',Kategori:'J'},
  {Kode:'63120',Judul:'Portal Web',Kategori:'J'},
  {Kode:'63910',Judul:'Aktivitas Kantor Berita',Kategori:'J'},
  {Kode:'63990',Judul:'Aktivitas Jasa Informasi Lainnya',Kategori:'J'},
  // ===== K: AKTIVITAS KEUANGAN DAN ASURANSI =====
  {Kode:'64110',Judul:'Bank Sentral',Kategori:'K'},
  {Kode:'64120',Judul:'Bank Umum',Kategori:'K'},
  {Kode:'64130',Judul:'Bank Perkreditan Rakyat (BPR)',Kategori:'K'},
  {Kode:'64141',Judul:'Koperasi Simpan Pinjam/Unit Simpan Pinjam',Kategori:'K'},
  {Kode:'64142',Judul:'Lembaga Keuangan Bukan Bank',Kategori:'K'},
  {Kode:'64191',Judul:'Pegadaian',Kategori:'K'},
  {Kode:'64192',Judul:'Aktivitas Perbankan Syariah',Kategori:'K'},
  {Kode:'64199',Judul:'Intermediasi Keuangan Lainnya',Kategori:'K'},
  {Kode:'64200',Judul:'Aktivitas Perusahaan Holding',Kategori:'K'},
  {Kode:'64301',Judul:'Reksa Dana',Kategori:'K'},
  {Kode:'64302',Judul:'Dana Pensiun',Kategori:'K'},
  {Kode:'64309',Judul:'Perantara Keuangan Lainnya',Kategori:'K'},
  {Kode:'64910',Judul:'Sewa Guna Usaha (Leasing)',Kategori:'K'},
  {Kode:'64921',Judul:'Aktivitas Kredit',Kategori:'K'},
  {Kode:'64922',Judul:'Penyaluran Pembiayaan',Kategori:'K'},
  {Kode:'64929',Judul:'Aktivitas Kredit Lainnya',Kategori:'K'},
  {Kode:'64991',Judul:'Perusahaan Modal Ventura',Kategori:'K'},
  {Kode:'64999',Judul:'Jasa Keuangan Lainnya',Kategori:'K'},
  {Kode:'65111',Judul:'Asuransi Jiwa',Kategori:'K'},
  {Kode:'65112',Judul:'Asuransi Jiwa Syariah',Kategori:'K'},
  {Kode:'65120',Judul:'Asuransi Kerugian',Kategori:'K'},
  {Kode:'65130',Judul:'Reasuransi',Kategori:'K'},
  {Kode:'65200',Judul:'Dana Pensiun',Kategori:'K'},
  {Kode:'65300',Judul:'Aktivitas Jaminan Sosial Wajib',Kategori:'K'},
  {Kode:'66110',Judul:'Administrasi Pasar Modal',Kategori:'K'},
  {Kode:'66120',Judul:'Aktivitas Perantara Pedagang Efek dan Komoditi',Kategori:'K'},
  {Kode:'66190',Judul:'Aktivitas Penunjang Jasa Keuangan Lainnya',Kategori:'K'},
  {Kode:'66210',Judul:'Penilaian Risiko dan Kerugian',Kategori:'K'},
  {Kode:'66220',Judul:'Aktivitas Agen dan Broker Asuransi',Kategori:'K'},
  {Kode:'66290',Judul:'Aktivitas Penunjang Asuransi dan Dana Pensiun Lainnya',Kategori:'K'},
  {Kode:'66300',Judul:'Aktivitas Manajemen Aset',Kategori:'K'},
  // ===== L: REAL ESTAT =====
  {Kode:'68110',Judul:'Real Estat yang Dimiliki Sendiri atau Disewa',Kategori:'L'},
  {Kode:'68120',Judul:'Real Estat Atas Dasar Balas Jasa atau Kontrak',Kategori:'L'},
  {Kode:'68130',Judul:'Kawasan Wisata dan Taman Rekreasi',Kategori:'L'},
  {Kode:'68200',Judul:'Kawasan Industri dan Pergudangan',Kategori:'L'},
  // ===== M: AKTIVITAS PROFESIONAL, ILMIAH DAN TEKNIS =====
  {Kode:'69101',Judul:'Aktivitas Hukum (Kantor Pengacara, Notaris, dll)',Kategori:'M'},
  {Kode:'69102',Judul:'Aktivitas Kenotariatan',Kategori:'M'},
  {Kode:'69200',Judul:'Aktivitas Akuntansi, Pembukuan dan Pemeriksa Keuangan',Kategori:'M'},
  {Kode:'70100',Judul:'Aktivitas Perusahaan Induk (Holding)',Kategori:'M'},
  {Kode:'70200',Judul:'Aktivitas Konsultasi Manajemen',Kategori:'M'},
  {Kode:'71101',Judul:'Aktivitas Arsitektur',Kategori:'M'},
  {Kode:'71102',Judul:'Aktivitas Keinsinyuran dan Konsultasi Teknis',Kategori:'M'},
  {Kode:'71103',Judul:'Aktivitas Survei Bangunan',Kategori:'M'},
  {Kode:'71200',Judul:'Pengujian dan Analisis Teknis',Kategori:'M'},
  {Kode:'72101',Judul:'Penelitian dan Pengembangan Ilmu Pengetahuan Alam',Kategori:'M'},
  {Kode:'72102',Judul:'Penelitian dan Pengembangan Teknologi',Kategori:'M'},
  {Kode:'72200',Judul:'Penelitian dan Pengembangan Ilmu Pengetahuan Sosial dan Humaniora',Kategori:'M'},
  {Kode:'73100',Judul:'Periklanan',Kategori:'M'},
  {Kode:'73200',Judul:'Penelitian Pasar dan Jajak Pendapat',Kategori:'M'},
  {Kode:'74101',Judul:'Aktivitas Desain Interior',Kategori:'M'},
  {Kode:'74102',Judul:'Aktivitas Desain Produk dan Industri',Kategori:'M'},
  {Kode:'74103',Judul:'Aktivitas Desain Tekstil dan Mode',Kategori:'M'},
  {Kode:'74104',Judul:'Aktivitas Desain Grafis',Kategori:'M'},
  {Kode:'74200',Judul:'Aktivitas Fotografi',Kategori:'M'},
  {Kode:'74300',Judul:'Aktivitas Penerjemahan dan Interpretasi',Kategori:'M'},
  {Kode:'74900',Judul:'Aktivitas Profesional, Ilmiah dan Teknis Lainnya',Kategori:'M'},
  {Kode:'75000',Judul:'Aktivitas Kesehatan Hewan',Kategori:'M'},
  // ===== N: AKTIVITAS PENYEWAAN =====
  {Kode:'77110',Judul:'Persewaan Mobil dan Kendaraan Bermotor Roda Empat',Kategori:'N'},
  {Kode:'77120',Judul:'Persewaan Kendaraan Bermotor Roda Dua',Kategori:'N'},
  {Kode:'77130',Judul:'Persewaan Kendaraan Darat Lainnya',Kategori:'N'},
  {Kode:'77210',Judul:'Persewaan Alat Rekreasi dan Olahraga',Kategori:'N'},
  {Kode:'77220',Judul:'Persewaan Video, DVD dan Sejenisnya',Kategori:'N'},
  {Kode:'77290',Judul:'Persewaan dan Leasing Barang Pribadi dan Rumah Tangga Lainnya',Kategori:'N'},
  {Kode:'77301',Judul:'Persewaan dan Leasing Mesin dan Peralatan Pertanian',Kategori:'N'},
  {Kode:'77302',Judul:'Persewaan dan Leasing Mesin dan Peralatan Konstruksi',Kategori:'N'},
  {Kode:'77303',Judul:'Persewaan dan Leasing Mesin Kantor dan Komputer',Kategori:'N'},
  {Kode:'77309',Judul:'Persewaan dan Leasing Mesin Lainnya',Kategori:'N'},
  {Kode:'77400',Judul:'Leasing Sumber Daya Intelektual dan Produk Sejenis',Kategori:'N'},
  {Kode:'78101',Judul:'Aktivitas Penempatan Tenaga Kerja',Kategori:'N'},
  {Kode:'78102',Judul:'Aktivitas Penyalur Tenaga Kerja',Kategori:'N'},
  {Kode:'78200',Judul:'Aktivitas Penyedia Tenaga Kerja Sementara',Kategori:'N'},
  {Kode:'78300',Judul:'Penyediaan dan Manajemen Sumber Daya Manusia Lainnya',Kategori:'N'},
  {Kode:'79110',Judul:'Aktivitas Agen Perjalanan',Kategori:'N'},
  {Kode:'79120',Judul:'Aktivitas Biro Perjalanan Wisata',Kategori:'N'},
  {Kode:'79130',Judul:'Pemandu Wisata',Kategori:'N'},
  {Kode:'79190',Judul:'Aktivitas Agen dan Biro Perjalanan Lainnya',Kategori:'N'},
  {Kode:'79900',Judul:'Jasa Reservasi dan Jasa Penunjang Perjalanan Lainnya',Kategori:'N'},
  {Kode:'80100',Judul:'Aktivitas Keamanan Swasta',Kategori:'N'},
  {Kode:'80200',Judul:'Aktivitas Jasa Sistem Keamanan',Kategori:'N'},
  {Kode:'80300',Judul:'Aktivitas Penyelidikan',Kategori:'N'},
  {Kode:'81100',Judul:'Aktivitas Kombinasi Jasa Penunjang Fasilitas',Kategori:'N'},
  {Kode:'81210',Judul:'Pembersihan Bangunan dan Industri',Kategori:'N'},
  {Kode:'81220',Judul:'Pembersihan Gedung, Ruang, dan Perlengkapannya',Kategori:'N'},
  {Kode:'81290',Judul:'Aktivitas Pembersihan Lainnya',Kategori:'N'},
  {Kode:'81300',Judul:'Aktivitas Pertamanan dan Perawatan Taman',Kategori:'N'},
  {Kode:'82110',Judul:'Aktivitas Administrasi Kantor',Kategori:'N'},
  {Kode:'82120',Judul:'Jasa Fotokopi, Persiapan Dokumen dan Jasa Khusus Administrasi Perkantoran Lainnya',Kategori:'N'},
  {Kode:'82190',Judul:'Aktivitas Penunjang Perkantoran Lainnya',Kategori:'N'},
  {Kode:'82200',Judul:'Aktivitas Call Centre',Kategori:'N'},
  {Kode:'82300',Judul:'Aktivitas Penyelenggaraan Konvensi dan Pameran Dagang',Kategori:'N'},
  {Kode:'82910',Judul:'Aktivitas Penagihan Utang dan Lembaga Perkreditan',Kategori:'N'},
  {Kode:'82920',Judul:'Aktivitas Pengepakan',Kategori:'N'},
  {Kode:'82990',Judul:'Aktivitas Penunjang Usaha Lainnya',Kategori:'N'},
  // ===== O: ADMINISTRASI PEMERINTAHAN =====
  {Kode:'84111',Judul:'Administrasi Pemerintahan Umum Pusat',Kategori:'O'},
  {Kode:'84112',Judul:'Administrasi Pemerintahan Umum Daerah',Kategori:'O'},
  {Kode:'84113',Judul:'Administrasi Pemerintahan Desa',Kategori:'O'},
  {Kode:'84120',Judul:'Peningkatan Pemerintahan dalam Bidang Kesehatan, Pendidikan, Kebudayaan, dll',Kategori:'O'},
  {Kode:'84130',Judul:'Peningkatan Efisiensi Kegiatan dari Berbagai Bidang Ekonomi',Kategori:'O'},
  {Kode:'84210',Judul:'Hubungan Luar Negeri',Kategori:'O'},
  {Kode:'84220',Judul:'Pertahanan',Kategori:'O'},
  {Kode:'84230',Judul:'Peradilan dan Aktivitas Keadilan',Kategori:'O'},
  {Kode:'84240',Judul:'Aktivitas Kepolisian',Kategori:'O'},
  {Kode:'84250',Judul:'Aktivitas Pemadam Kebakaran dan Penyelamatan',Kategori:'O'},
  {Kode:'84300',Judul:'Jaminan Sosial Wajib',Kategori:'O'},
  // ===== P: PENDIDIKAN =====
  {Kode:'85101',Judul:'Pendidikan Dasar (SD dan Sederajat)',Kategori:'P'},
  {Kode:'85102',Judul:'Pendidikan Anak Usia Dini (PAUD)',Kategori:'P'},
  {Kode:'85201',Judul:'Pendidikan Menengah Umum (SMP dan Sederajat)',Kategori:'P'},
  {Kode:'85202',Judul:'Pendidikan Menengah Kejuruan (SMK dan Sederajat)',Kategori:'P'},
  {Kode:'85203',Judul:'Pendidikan Menengah Atas (SMA dan Sederajat)',Kategori:'P'},
  {Kode:'85300',Judul:'Pendidikan Tinggi',Kategori:'P'},
  {Kode:'85410',Judul:'Pendidikan Olahraga dan Rekreasi',Kategori:'P'},
  {Kode:'85420',Judul:'Pendidikan Kebudayaan',Kategori:'P'},
  {Kode:'85430',Judul:'Pendidikan Selain Olahraga dan Kebudayaan',Kategori:'P'},
  {Kode:'85490',Judul:'Pendidikan Lainnya',Kategori:'P'},
  {Kode:'85500',Judul:'Jasa Penunjang Pendidikan',Kategori:'P'},
  // ===== Q: AKTIVITAS KESEHATAN =====
  {Kode:'86101',Judul:'Rumah Sakit Umum',Kategori:'Q'},
  {Kode:'86102',Judul:'Rumah Sakit Khusus',Kategori:'Q'},
  {Kode:'86103',Judul:'Rumah Sakit Bersalin',Kategori:'Q'},
  {Kode:'86201',Judul:'Praktik Dokter Umum',Kategori:'Q'},
  {Kode:'86202',Judul:'Praktik Dokter Spesialis',Kategori:'Q'},
  {Kode:'86203',Judul:'Praktik Dokter Gigi',Kategori:'Q'},
  {Kode:'86204',Judul:'Klinik',Kategori:'Q'},
  {Kode:'86209',Judul:'Aktivitas Kesehatan Manusia Lainnya',Kategori:'Q'},
  {Kode:'86301',Judul:'Puskesmas',Kategori:'Q'},
  {Kode:'86302',Judul:'Posyandu',Kategori:'Q'},
  {Kode:'86309',Judul:'Aktivitas Pelayanan Kesehatan Masyarakat Lainnya',Kategori:'Q'},
  {Kode:'86901',Judul:'Laboratorium Medis',Kategori:'Q'},
  {Kode:'86902',Judul:'Apotek',Kategori:'Q'},
  {Kode:'86903',Judul:'Optik',Kategori:'Q'},
  {Kode:'86904',Judul:'Aktivitas Paramedis',Kategori:'Q'},
  {Kode:'86905',Judul:'Akupunktur dan Pengobatan Tradisional',Kategori:'Q'},
  {Kode:'86906',Judul:'Aktivitas Kebidanan',Kategori:'Q'},
  {Kode:'86907',Judul:'Jasa Pengiriman Darah dan Organ Tubuh',Kategori:'Q'},
  {Kode:'86909',Judul:'Aktivitas Kesehatan Lainnya',Kategori:'Q'},
  {Kode:'87101',Judul:'Aktivitas Panti Jompo',Kategori:'Q'},
  {Kode:'87102',Judul:'Aktivitas Panti Rehabilitasi',Kategori:'Q'},
  {Kode:'87200',Judul:'Aktivitas Sosial Dalam Panti Untuk Penyandang Disabilitas Mental',Kategori:'Q'},
  {Kode:'87300',Judul:'Aktivitas Sosial Dalam Panti Untuk Manula dan Penyandang Disabilitas',Kategori:'Q'},
  {Kode:'87900',Judul:'Aktivitas Sosial Dalam Panti Lainnya',Kategori:'Q'},
  {Kode:'88101',Judul:'Aktivitas Sosial Tanpa Akomodasi untuk Lansia',Kategori:'Q'},
  {Kode:'88102',Judul:'Aktivitas Sosial Tanpa Akomodasi untuk Penyandang Disabilitas',Kategori:'Q'},
  {Kode:'88901',Judul:'Aktivitas Organisasi Sosial Kemasyarakatan',Kategori:'Q'},
  {Kode:'88909',Judul:'Aktivitas Sosial Tanpa Akomodasi Lainnya',Kategori:'Q'},
  // ===== R: KESENIAN, HIBURAN DAN REKREASI =====
  {Kode:'90001',Judul:'Seni Pertunjukan',Kategori:'R'},
  {Kode:'90002',Judul:'Aktivitas Penunjang Seni Pertunjukan',Kategori:'R'},
  {Kode:'90003',Judul:'Aktivitas Kreatif, Seni dan Hiburan Lainnya',Kategori:'R'},
  {Kode:'91011',Judul:'Aktivitas Perpustakaan',Kategori:'R'},
  {Kode:'91012',Judul:'Aktivitas Arsip',Kategori:'R'},
  {Kode:'91020',Judul:'Aktivitas Museum',Kategori:'R'},
  {Kode:'91030',Judul:'Aktivitas Situs Sejarah dan Budaya',Kategori:'R'},
  {Kode:'91040',Judul:'Aktivitas Kebun Binatang dan Taman Botani',Kategori:'R'},
  {Kode:'92000',Judul:'Aktivitas Perjudian dan Pertaruhan',Kategori:'R'},
  {Kode:'93111',Judul:'Aktivitas Fasilitas Olahraga',Kategori:'R'},
  {Kode:'93112',Judul:'Aktivitas Pusat Kebugaran',Kategori:'R'},
  {Kode:'93113',Judul:'Aktivitas Kolam Renang',Kategori:'R'},
  {Kode:'93119',Judul:'Aktivitas Fasilitas Olahraga Lainnya',Kategori:'R'},
  {Kode:'93120',Judul:'Aktivitas Klub Olahraga',Kategori:'R'},
  {Kode:'93130',Judul:'Aktivitas Pusat Kebugaran',Kategori:'R'},
  {Kode:'93191',Judul:'Aktivitas Balapan dan Pacuan Hewan',Kategori:'R'},
  {Kode:'93199',Judul:'Aktivitas Olahraga Lainnya',Kategori:'R'},
  {Kode:'93210',Judul:'Aktivitas Taman Hiburan dan Taman Bertema',Kategori:'R'},
  {Kode:'93291',Judul:'Aktivitas Rekreasi di Pantai dan Perairan',Kategori:'R'},
  {Kode:'93292',Judul:'Aktivitas Rekreasi di Alam',Kategori:'R'},
  {Kode:'93293',Judul:'Aktivitas Warnet dan Warung Game',Kategori:'R'},
  {Kode:'93299',Judul:'Aktivitas Hiburan dan Rekreasi Lainnya',Kategori:'R'},
  // ===== S: AKTIVITAS JASA LAINNYA =====
  {Kode:'94110',Judul:'Aktivitas Organisasi Bisnis dan Pengusaha',Kategori:'S'},
  {Kode:'94120',Judul:'Aktivitas Organisasi Profesi',Kategori:'S'},
  {Kode:'94200',Judul:'Aktivitas Serikat Pekerja',Kategori:'S'},
  {Kode:'94910',Judul:'Aktivitas Organisasi Keagamaan',Kategori:'S'},
  {Kode:'94920',Judul:'Aktivitas Organisasi Politik',Kategori:'S'},
  {Kode:'94990',Judul:'Aktivitas Organisasi Kemasyarakatan Lainnya',Kategori:'S'},
  {Kode:'95110',Judul:'Reparasi Komputer dan Peralatan Periferalnya',Kategori:'S'},
  {Kode:'95120',Judul:'Reparasi Peralatan Komunikasi',Kategori:'S'},
  {Kode:'95210',Judul:'Reparasi Peralatan Elektronik Konsumen',Kategori:'S'},
  {Kode:'95220',Judul:'Reparasi Peralatan Rumah Tangga dan Peralatan Rumah Tangga',Kategori:'S'},
  {Kode:'95230',Judul:'Reparasi Alas Kaki dan Barang dari Kulit',Kategori:'S'},
  {Kode:'95240',Judul:'Reparasi Furnitur dan Perlengkapan Rumah',Kategori:'S'},
  {Kode:'95290',Judul:'Reparasi Barang Keperluan Pribadi dan Rumah Tangga Lainnya',Kategori:'S'},
  {Kode:'96011',Judul:'Jasa Laundri dan Penatu',Kategori:'S'},
  {Kode:'96012',Judul:'Jasa Binatu',Kategori:'S'},
  {Kode:'96020',Judul:'Jasa Perawatan Rambut dan Kecantikan',Kategori:'S'},
  {Kode:'96031',Judul:'Jasa Pemakaman dan Kremasi',Kategori:'S'},
  {Kode:'96032',Judul:'Jasa Pengurusan Jenazah',Kategori:'S'},
  {Kode:'96040',Judul:'Aktivitas Kebugaran dan SPA',Kategori:'S'},
  {Kode:'96091',Judul:'Jasa Tato, Tindik, dan Sejenisnya',Kategori:'S'},
  {Kode:'96092',Judul:'Jasa Pengasuhan Bayi dan Anak',Kategori:'S'},
  {Kode:'96093',Judul:'Jasa Perawatan Hewan Peliharaan',Kategori:'S'},
  {Kode:'96099',Judul:'Aktivitas Jasa Perorangan Lainnya',Kategori:'S'},
  // ===== T: AKTIVITAS RUMAH TANGGA =====
  {Kode:'97000',Judul:'Aktivitas Rumah Tangga Sebagai Pemberi Kerja dari Personil Domestik',Kategori:'T'},
  {Kode:'98100',Judul:'Aktivitas yang Menghasilkan Barang oleh Rumah Tangga',Kategori:'T'},
  {Kode:'98200',Judul:'Aktivitas yang Menghasilkan Jasa oleh Rumah Tangga',Kategori:'T'},
  // ===== U: AKTIVITAS BADAN INTERNASIONAL =====
  {Kode:'99000',Judul:'Aktivitas Badan Internasional dan Badan Ekstra Internasional Lainnya',Kategori:'U'},
];

const STATIC_PROVINSI = [
  {kode:'11',nama:'ACEH'},{kode:'12',nama:'SUMATERA UTARA'},
  {kode:'13',nama:'SUMATERA BARAT'},{kode:'14',nama:'RIAU'},
  {kode:'15',nama:'JAMBI'},{kode:'16',nama:'SUMATERA SELATAN'},
  {kode:'17',nama:'BENGKULU'},{kode:'18',nama:'LAMPUNG'},
  {kode:'19',nama:'KEP. BANGKA BELITUNG'},{kode:'21',nama:'KEP. RIAU'},
  {kode:'31',nama:'DKI JAKARTA'},{kode:'32',nama:'JAWA BARAT'},
  {kode:'33',nama:'JAWA TENGAH'},{kode:'34',nama:'DI YOGYAKARTA'},
  {kode:'35',nama:'JAWA TIMUR'},{kode:'36',nama:'BANTEN'},
  {kode:'51',nama:'BALI'},{kode:'52',nama:'NUSA TENGGARA BARAT'},
  {kode:'53',nama:'NUSA TENGGARA TIMUR'},{kode:'61',nama:'KALIMANTAN BARAT'},
  {kode:'62',nama:'KALIMANTAN TENGAH'},{kode:'63',nama:'KALIMANTAN SELATAN'},
  {kode:'64',nama:'KALIMANTAN TIMUR'},{kode:'65',nama:'KALIMANTAN UTARA'},
  {kode:'71',nama:'SULAWESI UTARA'},{kode:'72',nama:'SULAWESI TENGAH'},
  {kode:'73',nama:'SULAWESI SELATAN'},{kode:'74',nama:'SULAWESI TENGGARA'},
  {kode:'75',nama:'GORONTALO'},{kode:'76',nama:'SULAWESI BARAT'},
  {kode:'81',nama:'MALUKU'},{kode:'82',nama:'MALUKU UTARA'},
  {kode:'91',nama:'PAPUA BARAT'},{kode:'92',nama:'PAPUA'},
  {kode:'93',nama:'PAPUA SELATAN'},{kode:'94',nama:'PAPUA TENGAH'},
  {kode:'95',nama:'PAPUA PEGUNUNGAN'},{kode:'96',nama:'PAPUA BARAT DAYA'},
];
