#!/usr/bin/env node
/**
 * tools/build-html.js — concatenate src/index/*.html partials → index.html
 *
 * Usage:
 *   node tools/build-html.js
 *   npm run build:html      (via package.json script)
 *
 * Partial naming convention: NN-name.html where NN is a 2-digit order prefix.
 * Files are concatenated in lexical order so the prefix governs the layout.
 *
 * Output: project root index.html (overwritten).
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT      = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PARTIALS  = resolve(ROOT, 'src/index');
const OUT_FILE  = resolve(ROOT, 'index.html');

function main() {
  const files = readdirSync(PARTIALS)
    .filter(f => f.endsWith('.html'))
    .sort(); // lexical sort honors 01-, 02-, ... ordering

  if (!files.length) {
    console.error('No partials found in src/index/');
    process.exit(1);
  }

  const banner = `<!--\n  AUTO-GENERATED by tools/build-html.js — DO NOT EDIT DIRECTLY.\n  Source partials: src/index/\n  Regenerate: npm run build:html\n-->\n`;

  let total = 0;
  const chunks = files.map(name => {
    const body = readFileSync(resolve(PARTIALS, name), 'utf8');
    total += body.split('\n').length;
    return body;
  });

  // Insert build banner right after the <!DOCTYPE html> line, before <html>
  let out = chunks.join('');
  out = out.replace(/^(<!DOCTYPE[^>]*>\n)/i, `$1${banner}`);

  writeFileSync(OUT_FILE, out, 'utf8');
  console.log(`✓ Built ${OUT_FILE} from ${files.length} partials (~${total} lines)`);
  files.forEach(f => console.log(`  • ${f}`));
}

main();
